version: '3'
services:
    web:
        build: .
        container_name: web
        ports:
            - 3000:3000
        networks:
            - nodeapp
        environment:
            - EV_PORT=3004
            - APP_PORT_HTTPS=3004
            - DB_HOST=localhost
            - DB_PORT=27018
            - DB_NAME=jwt-auth
            - ENV=development
            - JWT_SECRET=486f805PXd0k705c9q5EZ95yF
        volumes:
            - './src:/app/src'
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/mongodb
        ports:
            - '27018:27017'
        networks:
            - nodeapp
networks:
    nodeapp:
        driver: bridge
